#!/usr/bin/env python3

import os
import json

import redisjobs as jobs

from utils import persistence


def backup(config):
    try:
        board = jobs.Board(host=config['JOBS_REDIS_HOST'])
        serialization = board.dump()
    except:
        raise IOError('Could not get job listing from Jobs. Redis or the scheduler might be offline.')

    count = len(serialization['jobs']):

    if not count:
        return 0

    dump = json.dumps(serialization)
    path = os.path.join(location.path.lstrip('/'), 'jobs.json')
    mime = 'application/json'
    persistence.to_file(dump, path, 'social-shares', mime)

    return count


if __name__ == '__main__':
    count = backup(os.environ)
    if count:
        persistence.to_monitor('backup', n=1)
        print('Backed up {} jobs to Amazon S3.'.format(count))
    else:
        print('Skipped backup. The scheduler responded but did not have any jobs.')
