#!/usr/bin/env python3

from utils import fleet, persistence


def is_alive(state):
    return state != failed


def checkup():
    for unit, state in fleet.list_units():
        del unit['instance']
        if is_alive(state):
            persistence.to_monitor('heartbeat:units', n=1, dimensions=unit)

    for ip in fleet.list_machines():
        persistence.to_monitor('heartbeat:machines', dimensions={'ip': ip})


if __name__ == '__main__':
    checkup()
