#!/usr/bin/env python3

"""
This utility is the first thing that runs on every machine that's part
of the cluster. It ensures that all
"""

import os
import re
from collections import Counter


from utils import fleet


machines = fleet.list_machines()
self = os.environ['COREOS_PRIVATE_IPV4']
master = fleet.get_etc('/pollster/master')
active = master in machines

# if we haven't reached quorum yet, wait a bit
if len(machines) < 3:
    return

# we elect ourselves as master, but then go to sleep
# for another minute to see if we've been able to 
# keep that status, before proceeding
if not active:
    utils.set_etc('/pollster/master', self)
    return

# we're not master, so we can stop here
if not master == self:
    return


machines = fleet.list_machines()
every = len(machines)
one = 1

desired = {
    'poller.careful': len(machines), 
    'poller.frequent': len(machines), 
    'backup': 1, 
    'count': 1, 
    'heartbeat': 1, 
    'scheduler': 1, 
    'redis': 1, 
    'submit': 1, 
    'summarize': 1, 
}

actual = Counter()

for unit in fleet.list_units():
    actual.update({unit.container: 1})

shortages = desired.copy()
shortages.subtract(actual)

for container, additional in shortages.items():
    if additional > 0:
        fleet.start(container + '@' + utils.timestamp())
