#!/usr/bin/env python3

import sys
import os
import time
import json
import functools
from copy import copy
from collections import namedtuple

import socialshares
import redisjobs as jobs

from utils import flatten, persistence, environment


def register(instance):
    region = os.environ['AWS_REGION']
    name = 'pollster-blocked-' + instance
    actions = ['arn:aws:automate:eu-west-1:ec2:terminate']
    if os.getenv('POLLSTER_SNS'):
        actions.append(os.getenv('POLLSTER_SNS'))

    alarm = persistence.MetricAlarm(
        connection=None, 
        name=name, 
        metric='blocked', 
        dimensions={
            'InstanceId': instance, 
        }, 
        namespace='social-shares', 
        statistic='Average', 
        comparison='>=', 
        threshold=0.2, 
        period=300, 
        evaluation_periods=5, 
        description='Has this instance been rate limited or blocked by any third-party API?', 
        alarm_actions=actions, 
        )

    persistence.cloudwatch.put_metric_alarm(alarm)


def fetch(requested_platforms, meta):
    url = meta['payload']
    counts = socialshares.fetch(url, requested_platforms, attempts=1)
    platforms = counts.keys()
    item = copy(counts)
    item['url'] = url
    item['timestamp'] = int(time.time())
    persistence.to_console('Fetched {platforms} counts for {url}', 
        platforms=', '.join(platforms), url=url)
    persistence.to_queue(flatten(item), os.environ['POLLSTER_SQS'])
    persistence.to_db(flatten(item), os.environ['POLLSTER_DYNAMODB'])
    for platform in platforms:
        persistence.to_monitor('poll', { 
            'InstanceId': environment.get_instance_id(),
            'platform': platform, 
            })

    blocked_platforms = len(set(requested_platforms).difference(platforms))
    persistence.to_monitor('blocked', n=blocked_platforms, dimensions={
            'InstanceId': environment.get_instance_id(),        
        })

schedules = {
    'frequent': ['facebook', 'twitter'], 
    'careful': ['facebookfql', 'pinterest', 'linkedin', 'google'], 
}

if __name__ == '__main__':
    register(environment.get_instance_id())
    board = jobs.Board(host=os.environ['JOBS_REDIS_HOST'])
    schedule = sys.argv[1]
    platforms = schedules[schedule]
    fetcher = functools.partial(fetch, platforms)
    persistence.to_console('Start responding to {schedule} jobs', schedule=schedule)
    board.respond('pollster/' + schedule, fetcher)
