                #cloud-config

                coreos:
                  units:
                    - name: etcd.service
                      command: start
                    - name: fleet.service
                      command: start
                    #- name: master.service
                    #  command: start
                    #  content: 
                  etcd:
                    addr: $private_ipv4:4001
                    peer-addr: $private_ipv4:7001
                    discovery: 