                #cloud-config

                coreos:
                  update:
                    reboot-strategy: off
                  units:
                    - name: etcd.service
                      command: start
                    - name: fleet.service
                      command: start
                  etcd2:
                    advertise-client-urls: 'http://$private_ipv4:2379'
                    initial-advertise-peer-urls: 'http://$private_ipv4:2380'
                    listen-client-urls: 'http://0.0.0.0:2379,http://0.0.0.0:4001'
                    listen-peer-urls: 'http://$private_ipv4:2380,http://$private_ipv4:7001'
                  etcd:
                    addr: $private_ipv4:4001
                    peer-addr: $private_ipv4:7001
                    cluster-active-size: 5
                    cluster-remove-delay: 180.0
                    discovery: 