                #cloud-config

                coreos:
                  update:
                    reboot-strategy: off
                  units:
                    - name: etcd.service
                      command: start
                    - name: fleet.service
                      command: start
                  etcd:
                    addr: $private_ipv4:2379
                    peer-addr: $private_ipv4:2380
                    cluster-active-size: 5
                    cluster-remove-delay: 180.0
                    discovery: 