AWSTemplateFormatVersion: '2010-09-09'
Description: Pollster data stack

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: social-shares
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: url
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: social-shares
