#!/usr/bin/env python

import os
import json
from urlparse import urlparse
from boto.s3.connection import S3Connection
from boto.s3.key import Key
import redisjobs as jobs


def backup(config):
    board = jobs.Board(host=config['JOBS_REDIS_HOST'])
    dump = json.dumps(board.dump())
    s3 = S3Connection(
        config['AWS_ACCESS_KEY_ID'], 
        config['AWS_SECRET_ACCESS_KEY'], 
        )
    location = urlparse(config['POLLSTER_S3'])
    bucket = s3.get_bucket(location.hostname, validate=False)  
    output = Key(bucket)
    output.key = os.path.join(location.path.lstrip('/'), 'jobs.json')
    output.content_type = 'application/json'
    output.set_contents_from_string(dump)


if __name__ == '__main__':
    backup(os.environ)
    print 'Backed up jobs to Amazon S3.'
    #print 'Could not get job listing from Jobs. Redis or the scheduler might be offline.'
