#!/usr/bin/env python

import sys
import os
import time
import json
from copy import copy
from urlparse import urlparse
from collections import namedtuple
import socialshares
from boto import dynamodb2, sqs
from boto.dynamodb2.table import Table
from boto.ec2 import cloudwatch
import redisjobs as jobs


def flatten(obj, skip=[], connector='_', parent_key=''):
    items = []

    for sub_key, v in obj.items():
        if parent_key:
            key = parent_key + connector + sub_key
        else:
            key = sub_key

        if isinstance(v, dict) and not (key in skip):
            items.extend(flatten(v, skip, connector, key).items())
        elif isinstance(v, list):
            items.append((key, v))
        else:
            items.append((key, v))

    return dict(items)

def to_sqs(obj, config):
    connection = sqs.connect_to_region(
        config.region, 
        aws_access_key_id=config.username,
        aws_secret_access_key=config.password, 
        )
    queue = connection.get_queue('social-shares')
    message = sqs.message.RawMessage()
    message.set_body(json.dumps(obj))
    queue.write(message)

def to_dynamodb(obj, config):
    connection = dynamodb2.connect_to_region(
        config.region,
        aws_access_key_id=config.username,
        aws_secret_access_key=config.password,
        )
    table = Table('social-shares', connection=connection)
    table.put_item(data=obj)

def to_console(url, keys):
    platforms = ', '.join(keys)
    print 'Fetched {} counts for {}'.format(platforms, url)

def to_cloudwatch(keys, config):
    connection = cloudwatch.connect_to_region(
        config.region, 
        aws_access_key_id=config.username, 
        aws_secret_access_key=config.password, 
        )
    connection.put_metric_data('social-shares', 'any', value=1, unit='Count')
    for key in keys:
        connection.put_metric_data('social-shares', key, value=1, unit='Count')

Credentials = namedtuple('Credentials', ['region', 'username', 'password'])

def env(key):
    values = urlparse(os.environ[key])
    region = values.hostname or os.environ.get('AWS_REGION')
    username = values.username or os.environ.get('AWS_ACCESS_KEY_ID')
    password = values.password or os.environ.get('AWS_SECRET_ACCESS_KEY')
    return Credentials(region, username, password)

def fetch(meta):
    url = meta['id']
    counts = socialshares.fetch(url, ['facebook', 'twitter'])
    platforms = counts.keys()
    item = copy(counts)
    item['url'] = url
    item['timestamp'] = int(time.time())
    to_sqs(flatten(item), env('POLLSTER_SQS'))
    to_dynamodb(flatten(item), env('POLLSTER_DYNAMODB'))
    to_cloudwatch(platforms, env('POLLSTER_CLOUDWATCH'))
    to_console(url, platforms)

if __name__ == '__main__':
    board = jobs.Board(host=os.environ['JOBS_REDIS_HOST'])
    board.respond('pollster', fetch)
